### ISSUE TITLE
Enable custom JSON serialization

### ISSUE THREAD

**Issue by mindfulwizard** [mattfrear/Swashbuckle.AspNetCore.Examples#11]
I need my example properties to be in PascalCase, and my enums to be rendered as strings.

Ideally this would be done with a service collection.

**Comment by mattfrear** [comment]
You can get PascalCase like so:

`[SwaggerResponseExample(HttpStatusCode.OK, typeof(PersonResponseExample), typeof(DefaultContractResolver))]`

To render enums as strings - I'd need to change the code to support that. I've got it working locally but need to think about it a bit more before pushing it. If you want to change the code locally in ExamplesOperationFilter.cs it's:
`var serializerSettings = new JsonSerializerSettings { ContractResolver = attr.ContractResolver, NullValueHandling = NullValueHandling.Ignore, Converters = new List<JsonConverter> { new StringEnumConverter() } };`

**Comment by mindfulwizard** [comment]
Thank you for the quick response!

**Comment by mattfrear** [comment]
I've added a new jsonConverter parameter which you can set like so:
`[SwaggerRequestExample(typeof(PersonRequest), typeof(PersonRequestExample), jsonConverter: typeof(StringEnumConverter))]`
to render enums as strings.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Examples/2.2.0
