### ISSUE TITLE
Media Type appearing in the UI for examples

### ISSUE THREAD

**Issue by freeranger** [mattfrear/Swashbuckle.AspNetCore.Examples#12]
Hi,

I'm using Swashbuckle.AstNetCore 1.0.0 with Swashbuckle.AspNetCore.Examples with version 2.1.1 of your package.

In the swagger UI I am seeing the media type as part of the model:

![image](https://user-images.githubusercontent.com/1401069/29885437-c4779f18-8dae-11e7-84fc-8f2263d82905.png)

Which I wasn't expecting - is there a way to stop this happening

**Comment by mattfrear** [comment]
Oh wow I never noticed that before - I'm not sure if there's a way to get
rid of it. I'll have a look when I get a chance.

-- 
*Matt Frear*
matt.frear@gmail.com

**Comment by mattfrear** [comment]
OK I've figure out why it's doing that, but I have to find time to write a fix and publish the NuGet package.

Offending line of code is in ExampleOperationFilter.cs:
```
            var examples = new Dictionary<string, object>
            {
                {
                    "application/json", provider.GetExamples()
                }
            };
```
I can't even remember why I create a Dictionary, it might have been to get the Request examples working cos it seems it's not needed for the Response examples...

**Comment by freeranger** [comment]
Thanks for the quick response - I'll take a look

**Comment by freeranger** [comment]
Hi - I took it out completely, so not used for request or response and it works fine in both cases.

**Comment by mattfrear** [comment]
Hmm when I took it out I wasn't seeing the Request examples being set correctly

**Comment by freeranger** [comment]
How strange - my requests and my responses are both fine now I have taken application/json out completely:
![image](https://user-images.githubusercontent.com/1401069/29994365-fca827c2-8fc5-11e7-9714-39eeb6187f40.png)
 and
![image](https://user-images.githubusercontent.com/1401069/29994371-1b6328ba-8fc6-11e7-857b-4cca871e14d0.png)

**Comment by mattfrear** [comment]
Can you post the code you've changed?

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Examples/2.2.0

**Comment by freeranger** [comment]
Here is my code with the change: https://github.com/freeranger/Swashbuckle.AspNetCore.Examples/commit/ee9469d98d11ec159ac77a2ffc428845cce87c2a

**Comment by mattfrear** [comment]
Thanks @freeranger, works great, so I was able to tidy up the code more. ac0090b3

**Comment by mattfrear** [comment]
I have reverted this change in 2.2.2, because the previous response example with the application/json was correct as per the Swagger 2.0 spec. So maybe it's a bug with either Swashbuckle or Swagger-ui as to why application/json is appearing in the UI.
