### ISSUE TITLE
Error responses not appearing in UI

### ISSUE THREAD

**Issue by freeranger** [mattfrear/Swashbuckle.AspNetCore.Examples#13]
Hi,

I am not seeing my error response examples in the swashbuckle UI.
I downloaded your repo and tried with your examples and get the same thing:

![image](https://user-images.githubusercontent.com/1401069/29911918-aeb20668-8e27-11e7-99f7-c7f86ee3258d.png)

ie, the defaults for error responses are being returned.

**Comment by mattfrear** [comment]
That's a known issues with Swagger UI
