### ISSUE TITLE
Any way to document url parameters?

### ISSUE THREAD

**Issue by freeranger** [mattfrear/Swashbuckle.AspNetCore.Examples#15]
Hi,

I have a url which would be something like `/api/countries/USA/population/2017-09-02` where "USA" and "2017-09-02" are parameters to the action.
The date is only accepted in this very specific format and I would like to document this fact - is there any way to add a request example like this?

thanks

**Comment by mattfrear** [comment]
You would have to change the DescriptionOperationFilter - it shouldn't be too hard to do that. I take pull requests :-)

**Comment by freeranger** [comment]
Hi @mattfrear - certainly willing to give it a go. I am new to .NET core and swashbuckle though so any pointers would be appreciated....

**Comment by mattfrear** [comment]
The tricky part will be figuring out where in the swagger document it needs to go - for that you'll have to dig through the swagger 2.0 spec.

I can do it when I get a chance - possibly some time this week.

**Comment by mattfrear** [comment]
Reading the Swagger spec it looks like each [parameter object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object) can have a description property so you should be able to set that

**Comment by freeranger** [comment]
Thanks Matt - turns out all I needed was to enable xml comments for swashbuckle and add comments for the params like:
`<param name="XXX">Describe XXX</param>`

**Comment by mattfrear** [comment]
Ah of course - I guess that's why I didn't implement this for request examples back when I did the DescriptionOperationFilter. Maybe I'll add a note to the readme.
