### ISSUE TITLE
Parameter examples?

### ISSUE THREAD

**Issue by CumpsD** [mattfrear/Swashbuckle.AspNetCore.Examples#20]
Would it be possible to add something for this https://swagger.io/docs/specification/adding-examples/#parameters ?

**Comment by mattfrear** [comment]
The spec you've linked to is the OpenAPI spec aka Swagger 3.0

As far as I'm aware, Swashbuckle was written against the Swagger 2.0 spec. I don't know if or when Swashbuckle will move to the OpenAPI spec, but when they do then your suggestion will be a good one.

For now, the parameters object in Swagger 2.0 doesn't have an examples property.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject
