### ISSUE TITLE
SwaggerRequestExample and array (Or List<T>)

### ISSUE THREAD

**Issue by JuanZamudioGBM** [mattfrear/Swashbuckle.AspNetCore.Examples#21]
Hi

Maybe I'm doing this wrong but i can't get my code to work, this is a method in my controller

```
[SwaggerRequestExample(typeof(NewOrderDto), typeof(NewOrderListExample))]
public async Task<IActionResult> AddOrderAsync([FromBody] List<NewOrderDto> orders)
```

My Example class returns this:
```
return new List<NewOrderDto>
{
    new NewOrderDto
    {
        Foo= "bla"
    },
    new NewOrderDto
    {
        Foo= "bla2"
    }
};
```

With that code, the request example object its just an object with default values, if i change the method to `public async Task<IActionResult> AddOrderAsync([FromBody] NewOrderDto orders)`  the example its added to the documentation.

I debugged the code in [ExamplesOperationFilter](https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/blob/4f3549a1b9609bc31ef1653f0c87a5b353c5d641/src/Swashbuckle.AspNetCore.Examples/ExamplesOperationFilter.cs) with List as the parameter and the validation fails here:

```
var request = bodyParameters.FirstOrDefault(p => p.Schema.Ref == schema.Ref);
if (request != null) /// does not enter here because  p.Schema.Ref  == null
```

I modified the class to enter another path when `ExamplesProviderType `is my type, but in that case, the example returned its a nested array `[ [ { "foo": "bla" }, { "foo": "bla2" } ] ]`

Its my input parameter wrong or I'm not decorating right my method?

Thanks a lot for your time

**Comment by safv12** [comment]
Same problem

**Comment by mattfrear** [comment]
Hi,

Yes, Lists aren't working in this package at the moment. I fixed the issue in the sister package a week ago, I need to port the same minor fix to this package when I get a chance.

https://github.com/mattfrear/Swashbuckle.Examples/issues/23

**Comment by JuanZamudioGBM** [comment]
Thanks for your time

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Examples/2.4.0
