### ISSUE TITLE
Method not found 'Newtonsoft.Json.JsonSerializerSettings.get_Binder()' after upgrading to Version="2.4.1"

### ISSUE THREAD

**Issue by dmitry-pavlov** [mattfrear/Swashbuckle.AspNetCore.Examples#23]
After upgrading to     <PackageReference Include="Swashbuckle.AspNetCore.Examples" Version="2.4.1" />
I am getting exception on Swagger UI run: 
Method not found: 'Newtonsoft.Json.SerializationBinder Newtonsoft.Json.JsonSerializerSettings.get_Binder()'

**Comment by mattfrear** [comment]
Oh dear. Do you get this problem with 2.4.0?

**Comment by mattfrear** [comment]
Can you post a stack trace?

**Comment by dmitry-pavlov** [comment]
Downgraded back to     <PackageReference Include="Swashbuckle.AspNetCore.Examples" Version="2.3.1" /> for a while, which works OK.

**Comment by dmitry-pavlov** [comment]
back to "Swashbuckle.AspNetCore.Examples" Version="2.3.1"

**Comment by dmitry-pavlov** [comment]
This is a separate issue. As for PR - I just wanted to add some improvements recently and finally managed to do that today :)

**Comment by mattfrear** [comment]
OK. I only released 2.4.1 yesterday, and I'm unable to reproduce your issue - are you able to reproduce it in my sample WebApi project?

**Comment by dmitry-pavlov** [comment]
I am trying to clean NuGet packages cache and rebuild everything from scratch in my project first. I have updated a bunch of packages today. And often such weird side effect might occur. If I reproduce it in a clean run I will provide here more details (will try to do that using sample Web API project). Otherwise I will close the issue if it will gone. Stay tuned :)

**Comment by dmitry-pavlov** [comment]
@mattfrear I keep getting the error with v 2.4.2. Here is the stack trace:
```
System.MissingMethodException: Method not found: 'Newtonsoft.Json.SerializationBinder Newtonsoft.Json.JsonSerializerSettings.get_Binder()'.
   at Swashbuckle.AspNetCore.Examples.ExamplesOperationFilter.DuplicateSerializerSettings(JsonSerializerSettings controllerSerializerSettings)
   at Swashbuckle.AspNetCore.Examples.ExamplesOperationFilter.SerializerSettings(IContractResolver attributeContractResolver, JsonConverter attributeJsonConverter)
   at Swashbuckle.AspNetCore.Examples.ExamplesOperationFilter.SetResponseModelExamples(Operation operation, ApiDescription apiDescription)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```
As for reproducing it with sample Web API - will do that later today or tomorrow.

**Comment by dmitry-pavlov** [comment]
@mattfrear as far as I understand it fails on this line https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/blob/master/src/Swashbuckle.AspNetCore.Examples/ExamplesOperationFilter.cs#L152 
You could try to update Swashbuckle.AspNetCore.Examples project to Standard 2.0 and WebApi project to Core 2.0 - as the Binder property is obsolete https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_Binder.htm

**Comment by dmitry-pavlov** [comment]
@mattfrear I can't reproduce the issue using sample Web API. I have created https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/pull/27  which updates it to .NET Standard 2.0 (and Web API to .NET Core 2.0). Maybe this will do a trick. Not sure. But anyway switching to the latest Core/Standard 2.0 makes sense anyway. Please review and consider to merge. Thanks!

**Comment by mattfrear** [comment]
Hmm, I disagree about it making sense to upgrade to the latest version. At my company we are using Swashbuckle.AspNetCore on .NET Framework 4.6, and other contributors in the past have requested this backwards compatibility.

Thank you for providing the stack trace. It sounds like maybe your solution is using a later version of Json.NET, one that as you say doesn't implement `Binder`. This code was copy and pasted from Swashbuckle.Examples in a recent PR, so it should be easy to fix - maybe even by just deleting that line.

**Comment by dmitry-pavlov** [comment]
Okay, it is up to you to decide. But please keep in mind that others might want to use it with Core 2.0 as well and it should be compatible with the latest stack :)

**Comment by dmitry-pavlov** [comment]
Also I didn't get why you need to Duplicate the settings - the code seemed to work fine without "cloning" the settings instance.

**Comment by mattfrear** [comment]
The idea was to clone the settings so that when `serializerSettings.ContractResolver = attributeContractResolver;` line is set, it doesn't overwrite the "global" serializer settings.

This code was taken from Swashbuckle.Examples in a PR #22 by @bhugot, and it IS needed there. 

However, it may not even be needed in this project, since the global settings are injected in via DI in the `IOptions<MvcJsonOptions> mvcJsonOptions`. I don't know if changing the `IOptions<MvcJsonOptions> mvcJsonOptions` changes the global settings or not. If it doesn't then we can remove that block.

**Comment by bhugot** [comment]
I can do better than that I think I will look at it. There is many changes between aspnetcore 1.1 and 2.0 but we could have a multitarget package that should fix those problems

**Comment by mattfrear** [comment]
I cannot reproduce this locally. I've tried twice, with a fresh .NET Core 2.0 web api, referencing latest Swashbuckle.AspNetCore and 2.4.2 of Swashbuckle.AspNetCore.Examples. It works fine.

I can confirm in my experimentation that we do need to call `DuplicateSerializerSettings`. If we don't, then when we change the Serializer's properties via the `jsonConverter: typeof(StringEnumConverter)` then that will affect the actual response returned by the API.

However, it seems like the obsolete Binder property is not needed, so I have commented it out and pushed a new NuGet package. @dmitry-pavlov can you try this version https://www.nuget.org/packages/Swashbuckle.AspNetCore.Examples/2.4.3?

**Comment by dmitry-pavlov** [comment]
@mattfrear with version 2.4.3 I don't have the issue. So it is fixed and could be closed here. Thanks!
