### ISSUE TITLE
Description is not supported for request models

### ISSUE THREAD

**Issue by dmitry-pavlov** [mattfrear/Swashbuckle.AspNetCore.Examples#26]
The description attribute ignored for request model properties.

**Comment by dmitry-pavlov** [comment]
I have created a PR which contains the fix for this bug here #24 
Please consider to merge to the master branch.

**Comment by mattfrear** [comment]
Merged, thank you.

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Examples/2.4.2
