### ISSUE TITLE
Each object can only has one example?

### ISSUE THREAD

**Issue by aidenZhou** [mattfrear/Swashbuckle.AspNetCore.Examples#28]
I have two APIs which they both take in the same object.  However , I need different examples for each object.
So what I have done is:

        [Route("ca/student/add")]
        [HttpPost]
        [SwaggerRequestExample(typeof(STUDENT), typeof(AddStudentExample))]
        public IHttpActionResult AddStudentRecord(STUDENT student)
        {
            return Ok(this._projectService.AddStudentData(student));
        }

        [Route("ca/student/update")]
        [HttpPost]
        [SwaggerRequestExample(typeof(STUDENT), typeof(UpdateStudentExample))]
        public IHttpActionResult UpdateStudentRecord(STUDENT student)
        {
            return Ok(this._projectService.UpdateStudentData(student));
        }

So I have created two different class as AddStudentExample and UpdateStudentExample
In each class the GetExamples() is returning a STUDENT object with different values.
But in the swagger, the example values shown for both of these two APIs are the value of UpdateStudentExample.
Is it possible for me to make these two APIs have different examples?
Thank you.

**Comment by mattfrear** [comment]
Nope, this is a limitation of the Swagger 2.0 spec - you can only have one example for each schema object, when the object is a request. Duplicate issue #19 . I also mention this in the Known Issues section of the readme. 

> For requests, in the Swagger 2.0 spec there is only one schema for each request object defined across all the API endpoints. So if you are using the same request object in multiple API endpoints, i.e. on multiple controller actions like this:

**Comment by freeranger** [comment]
@aidenZhou I had to create extra classes which do nothing other than inherit from the class I am actually interested in to get the desired behaviour.
So for you, you would have to create an UpdateStudent class inheriting from Student, which has no additional functionality, and then change your actions like this:
```
  [SwaggerRequestExample(typeof(UpdateStudent), typeof(UpdateStudentExample))]
  public IHttpActionResult UpdateStudentRecord(UpdateStudent student)
```
