### ISSUE TITLE
Values are not set in UI for multiple SwaggerResponseExample-s

### ISSUE THREAD

**Issue by dmitry-pavlov** [mattfrear/Swashbuckle.AspNetCore.Examples#29]
For instance [this line](https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/blob/master/src/WebApi/Controllers/ValuesController.cs#L24) states:
`[SwaggerResponseExample(404, typeof(NotFoundResponseExample))]`

NotFoundResponseExample initializes errorCode with 404 value. But Example Value in Swagger UI for test WebAPI project shows the default value for integer - 0.

Operation handling SwaggerResponseExample attribute should handle all attributes rather than only those which have the same response type as API action. 

@mattfrear please consider to fix.

**Comment by mattfrear** [comment]
Hi Dmitry,
> NotFoundResponseExample initializes errorCode with 404 value. But Example Value in Swagger UI for test WebAPI project shows the default value for integer - 0.

Can you check the output in the swagger.json file - does it look correct there? Because if the swagger.json looks correct, then it's a swagger-ui bug.

> Operation handling SwaggerResponseExample attribute should handle all attributes rather than only those which have the same response type as API action.

Sorry, I don't quite understand what you mean. Can you try explain again, or provide an example?

Matt

**Comment by dmitry-pavlov** [comment]
@mattfrear sure:

1. Run Web API 
2. Expand POST /api/Values/api/values/person
3. Check 404 response example
4. You will see it is 0 now, but should be 404

![screenshot 2017-12-27 14 17 34](https://user-images.githubusercontent.com/1560778/34380215-ea062550-eb10-11e7-8885-a9d058be3a17.png)

**Comment by mattfrear** [comment]
> Can you check the output in the swagger.json file - does it look correct there? Because if the swagger.json looks correct, then it's a swagger-ui bug.

Did you check the swagger.json? This is a very old swagger-ui bug.

![image](https://user-images.githubusercontent.com/169179/34381627-a84679bc-eb01-11e7-91ae-21982989a73f.png)

This is also listed on the Readme under "Known issues". https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples#known-issues 

> Although you can add a response examples for each HTTP status code (200, 201, 400, 404 etc), and they will all appear in the swagger.json, only one example for responses will display on the swagger-ui page. This is due to a bug in swagger-ui. Issue 9 You may want to use Swashbuckle's [SwaggerResponseRemoveDefaults] attribute to remove 200 from your list of response codes, if for example your API returns 201s and not 200

**Comment by dmitry-pavlov** [comment]
Ok. Got it. Thanks for clarifying!
