### ISSUE TITLE
The  example attribute can't  actually act on Controller Action

### ISSUE THREAD

**Issue by zhaokuohaha** [mattfrear/Swashbuckle.AspNetCore.Examples#31]
Hi : 
   I have a issue , in my code , it has two function use the same models, and i want to provide different example for both of them, like follow code : 

```csharp
public class DemoController : Controller {
  [SwaggerRequestExample(typeof(DemoModel ), typeof(ExampleOne))]
  public void ActionOne (DemoModel input){
    // do something
  }

  [SwaggerRequestExample(typeof(DemoModel ), typeof(ExampleTwo))]
  public void ActionTwo (DemoModel input){
    // do something
  }
}

public class DemoModel  {
  public string Name {get; set;}
}

public class ExampleOne : IExamplesProvider {
  public object GetExamples(){
    return new{
      Name = "Example One"
    }
}

public class ExampleTwo : IExamplesProvider {
  public object GetExamples(){
    return new{
      Name = "Example Two"
    }
}
```
I expect it show "Example One" on ActionOne example , and "Example Two" on ActionTwo example

However it both show "Example Two"  in fact.

**Comment by mattfrear** [comment]
You can only have one example for each Request object, this is stated on the "Known issues" section of the Readme.

**Comment by freeranger** [comment]
@zhaokuohaha See this thread: https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/issues/28

**Comment by zhaokuohaha** [comment]
@freeranger  @mattfrear  got it , thanks !
