### ISSUE TITLE
Possibility to exclude media type from example

### ISSUE THREAD

**Issue by marudenko** [mattfrear/Swashbuckle.AspNetCore.Examples#34]
Current version of ExamplesOperationFilter  always generate sample JSON with media type wrapper. Code already support possibility to generate pure example, but method FormatJson always called with parameter  includeMediaType=true.
It would be nice to setup that option when we construct ExamplesOperationFilter  
Thank you!

**Comment by mattfrear** [comment]
People have been asking for this already a lot. To do so would break the Swagger spec, therefore I will not do it.
