### ISSUE TITLE
Support SwaggerResponseExample at controller level?

### ISSUE THREAD

**Issue by TDabasinskas** [mattfrear/Swashbuckle.AspNetCore.Examples#37]
Hello,

Currently, `SwaggerResponseExample` attribute works only on methods (actions). Anyhow, if I would like to provide response examples for HTTP errors, that means I have to add the following duplicate code for every single action within a controller:

```csharp
[SwaggerResponseExample(StatusCodes.Status404NotFound, typeof(NotFoundErrorExample))]
[SwaggerResponseExample(StatusCodes.Status400BadRequest, typeof(BadRequestErrorExample))]
[SwaggerResponseExample(StatusCodes.Status401Unauthorized, typeof(UnauthorizedErrorExample))]
[SwaggerResponseExample(StatusCodes.Status403Forbidden, typeof(ForbiddenErrorExample))]
```

As any of the methods within a controller might return these responses, would it be possible to support them per controller (class) level? In that case, they could be automatically applied to all the actions, merging them with any per-action response examples?

This would also allow to be aligned with the way `ProducesResponseType` attribute works, at I currently can use it on a controller to define common response types (e.g. for 404) for all actions, as well as have it set per action for individual response types (e.g. for 200).

Maybe I'm not aware and there's another practice to define common responses with examples?

Thank you.

**Comment by mattfrear** [comment]
That's a good suggestion, I'll implement it when I get a chance

**Comment by mattfrear** [comment]
Released https://www.nuget.org/packages/Swashbuckle.AspNetCore.Examples/2.8.0
