### ISSUE TITLE
Readme refers to SwaggerResponse attributes

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [mattfrear/Swashbuckle.AspNetCore.Examples#38]
In Readme there are examples of SwaggerResponse
```
[SwaggerResponse(200, Type=typeof(IEnumerable<Country>))]
[SwaggerResponseExample(200, typeof(CountryExamples))]
[SwaggerResponse(400, Type = typeof(IEnumerable<ErrorResource>))]
public async Task<HttpResponseMessage> Get(string lang)
```
However "As of beta902, SwaggerResponse attributes have been removed in favor of the built in ProducesResponseType attributes."
From <https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/49> 

Please update the document

**Comment by mattfrear** [comment]
Not true. Swashbuckle.AspNetCore v1.0.0 supports SwaggerResponse, so he must have brought it back in again. I find the SwaggerResponse attribute better because it is more verbose as you can have a string description.
