### ISSUE TITLE
no support for net462

### ISSUE THREAD

**Issue by andrasg** [mattfrear/Swashbuckle.AspNetCore.Examples#4]
Is there a reason for not supporting net462 in aspnetcore? When referencing the library, dotnet restore complains that netstandard1.3 is not compatible with net462.

**Comment by WillGunn** [comment]
I've created a PR that should do that (We needed 4.6.1 locally, but it should also work for 4.6.2)
https://github.com/mattfrear/Swashbuckle.AspNetCore.Examples/pull/5

**Comment by mattfrear** [comment]
Hi guys,

Firstly apologies for the delay - I only just noticed this baclog of issues and PRs today as for some unknown reason GitHub hasn't been emailing me notifications.

I've have a look at this now.

**Comment by mattfrear** [comment]
Fixed in commit 579898b93936fb1ca355cb6e9e504e81d9921951
