### ISSUE TITLE
SwaggerRequestExample should not have to match the type in method

### ISSUE THREAD

**Issue by nycdanielp** [mattfrear/Swashbuckle.AspNetCore.Examples#42]
I have a method that takes a generic JObject, so it's not really defined anywhere what the contents should look like and thus it's hard to get an example. However, I later map that JObject to a specific type. So I would like to set this type in the SwaggerRequestExample and have that appear in the example because that will mirror what my request body should look like. I am able to to this with Swashbuckle.Examples. However, a fatal error occurs in Swashbuckle.AspNetCore.Examples when I attempt the same thing.

My SwaggerRequestExample attribute:
```csharp
[HttpPost]
[Route("api/ZipcodeGet")]
[SwaggerRequestExample(typeof(GetZipCodeRequest), typeof(DeliveryOptionsSearchModelExample))]
public IActionResult ZipcodeGet([FromBody] JObject request) => base.SendPost("ZipcodeGet", request);
```
My IExamplesProvider:

    public class DeliveryOptionsSearchModelExample : IExamplesProvider
    {
        public object GetExamples()
        {
            return new GetZipCodeRequest
            {
                zipCode = "37311"
            };
        }
    }

**Comment by mattfrear** [comment]
I have just pushed 2.8.2 which will fix the NullReferenceException, which was a bug I noticed a couple of weeks ago.

I don't believe that what you are trying to do works with Swashbuckle.Examples - I just tried in that project and it also throws a NullReferenceException.

What you are trying to do is currently unsupported - however, PR #40 might fix your issue. I haven't merged it in yet because it needs unit tests. I have a bit of spare time now so I will try get this done soon.

**Comment by nycdanielp** [comment]
It definitely works in Swashbuckle.Examples. I cloned that project from github and made a change to ListPeopleRequestExample. I did not alter the SwaggerRequestExample attribute, but I changed the IExamplesProvider, and found out that it doesn't check the return type. So the swagger output uses the object I return. This will appear in /api/values/listperson.

I altered the IExamplesProvider as follows:

namespace WebApi.Models.Examples
{
    internal class ListPeopleRequestExample : IExamplesProvider
    {
        public object GetExamples()
        {
            // return new PeopleRequest { Title = Title.Mr, Age = 24, FirstName = "Dave in a list", Income = null };

            return new Gender { IsMale = true };
        }
    }
}

You can see in the Swagger output, the example populates with the example output. This is the behavior that I hope to obtain in Swashbuckle.AspNetCore.Examples. I will test with your latest commit to see if it helps.

**Comment by mattfrear** [comment]
Right, but what does your controller look like? If it is unchanged
```
        public IHttpActionResult GetPersonList(List<PeopleRequest> peopleRequest)
        {
```
then yes it will work.
But if it has a JObject, like you want.
```
        public IHttpActionResult GetPersonList(JObject peopleRequest)
        {
```
Then I would be surprised if that works

**Comment by nycdanielp** [comment]
Correct, when I change to GetPersonList(List<JObject> peopleRequest) it no longer works in the Swashbuckle.Examples project. I pulled down your update to Swashbuckle.AspNetCore.Examples. It no longer throws a fatal error, but with the SwaggerRequestExample and IExamplesProvider I mentioned above (using JObject in method signature) it doesn't populate the example for the parameter in Swagger.

**Comment by mattfrear** [comment]
Do you really need to take a JObject as a parameter? Or a List<JObject>?

I have merged @antonGritsenko's PR, which added support for passing `Dictionary<string, object>`, in 2.9.0.

So you could do:
```csharp
[SwaggerRequestExample(typeof(Dictionary<string, object>), typeof(DeliveryOptionsSearchModelExample))]
public IActionResult ZipcodeGet([FromBody] Dictionary<string, object> request) => base.SendPost("ZipcodeGet", request);
```
Does that meet your needs?

**Comment by nycdanielp** [comment]
As it stands now, I do need to take a JObject as a parameter. I have basically this one endpoint that accepts json requests, and further down into the system they are deciphered and cast into types. So while I appreciate the updates and bug fixes, it's not exactly going to fix my issue. I do have a workaround I can use:

`public IActionResult ZipcodeGet([FromBody] GetZipCodeRequest request) => base.SendPost("ZipcodeGet", JObject.FromObject(request));`

Although ideally I wouldn't need to do this.
Thanks in any event.

**Comment by nycdanielp** [comment]
Actually, found a pretty simple fix - I will just have the IExamplesProvider return a JObject that I construct  - this will allow me to get an example for the JObject parameter.
Thanks again.
