### ISSUE TITLE
Additional response examples are not honoured

### ISSUE THREAD

**Issue by Stefan-Z-Camilleri** [mattfrear/Swashbuckle.AspNetCore.Examples#9]
Hi

First of all, thank you for your great library.

In my case, I've been working with this and even modified it a bit.  Yet either I am doing something wrong, or I don't know, but examples for additional responses are not being generated for me.

I am using v2.1.1

<img width="1613" alt="screen shot 2017-08-13 at 09 13 42" src="https://user-images.githubusercontent.com/20099218/29246948-c096c6c6-8007-11e7-81aa-6f00dad7dd36.png">

To the left is the minor modification I made to your library, which simply swaps out the `StatusCode` with a version that has a descriptive version (ex. `(200) OK`).

As you can see from the screenshot, the examples are being provided using `default` values... yet whilst debugging the `IOperationFilter` I can clearly see the example set correctly on the `Response.Examples` object.

p.s. this works fine for the request body.

### Additional info

The action
![screen shot 2017-08-13 at 09 16 08](https://user-images.githubusercontent.com/20099218/29246973-228e0e16-8008-11e7-9e23-37e86d425579.png)

One of the examples that is not output
![screen shot 2017-08-13 at 09 18 18](https://user-images.githubusercontent.com/20099218/29247124-67482e42-8008-11e7-8f9f-738aa7e8062d.png)

The example is clearly there during debug
![screen shot 2017-08-13 at 09 22 05](https://user-images.githubusercontent.com/20099218/29247626-eef376d0-8008-11e7-960c-84b273298867.png)

What am I missing?

**Comment by Stefan-Z-Camilleri** [comment]
Ok... so some debugging later, I realize the error is apparently in Swagger-UI or I believe SwashBuckle itself (`//TODO: I'll have to check the swagger spec to see who is actually wrong here`)

The examples for responses are generated as an `examples` property on the response (in line with the actual `Response` model that SwashBuckle uses.

![screen shot 2017-08-13 at 09 55 28](https://user-images.githubusercontent.com/20099218/29248023-91bf219e-800d-11e7-8f6f-e4d6f89943a7.png)

If we move this example to the actual schema definition (and rename it from `examples` to `example`, then everyone is happy:
![screen shot 2017-08-13 at 09 58 13](https://user-images.githubusercontent.com/20099218/29248037-f419b430-800d-11e7-96c8-3acd2e49cdd5.png)

Giving (pardon the styling... will clean that up later)
<img width="857" alt="screen shot 2017-08-13 at 09 58 52" src="https://user-images.githubusercontent.com/20099218/29248040-0a87a2b8-800e-11e7-9970-73892e5d8aa5.png">

I'm working on a fix.

**Comment by Stefan-Z-Camilleri** [comment]
This is a swagger-ui bug:

https://github.com/swagger-api/swagger-ui/issues/1213
https://github.com/swagger-api/swagger-ui/issues/1248
https://github.com/swagger-api/swagger-ui/issues/1213

This was fixed in 3.x ... alas SwashBuckle has not upgraded to 3.x yet, bar one fork on myget by another developer.

The temporary workaround for this is to add an example schema on the fly, using an `IOperationFilter` which is just for the example and modifying the schema ref on the response.

**Comment by mattfrear** [comment]
Hi Stefan,

Yes I noticed the bug you're describing a few months ago, and also found the same related swagger-ui bugs as you have found. However, I didn't find a workaround as you have done - nice work.

If you want to submit a PR for your workaround then I will accept it - but for me, personally, it's not a big issue and I'm happy to wait for the swagger-ui fix to be imported into Swashbuckle.

**Comment by Stefan-Z-Camilleri** [comment]
I'm not sure if I should submit a PR here @mattfrear as it is more of a hack than a fix.  What I am doing it the following:

1- I fetch the schema for the type
2- I clone the schema and rename the ref to a guid
3- I inject the examples into the new schema and add it to the collection using the new guid as key
4- I set the response schema ref to the ref the new schema

I also added a little hack for Swagger's limitation in rendering arrays, I create an `ExpandoObject` on the fly and add that as a schema... this is handy for example validation responses.

If you want this PR, I'll create it.. it's your call sir.

**Comment by mattfrear** [comment]
Ah ok, thanks - I'll leave it as-is then. Hopefully Swashbuckle will get the swagger-ui fix soon and then it'll all work correctly.

**Comment by freeranger** [comment]
@stefan-z-camiller

**Comment by mattfrear** [comment]
I think this is fixed as of Swashbuckle 2.0 which shipped with the new swagger-ui.
